### ISSUE TITLE
Cura crashes when refreshing OpenSCAD model

### ISSUE THREAD

**Issue by Ghostkeeper** [thopiekar/CuraOpenSCADPlugin#7]
I'm getting Cura to crash when I try to reload the file. These have been my reproduce steps:

* Load any .scad file.
* Press F5 to reload.

This is the log:

    2018-05-29 10:00:38,390 - INFO - [MainThread] cura.CuraApplication.reloadAll [1287]: Reloading all loaded mesh data.
    2018-05-29 10:00:38,396 - ERROR - [Thread-10] UM.Mesh.MeshFileHandler.readerRead [53]: [Errno 2] No such file or directory: '/tmp/588857ed-9c22-4366-b9e8-05413da474e4.STL'
    2018-05-29 10:00:38,397 - WARNING - [Thread-10] UM.Mesh.MeshFileHandler.readerRead [55]: Unable to read file /tmp/588857ed-9c22-4366-b9e8-05413da474e4.STL
    2018-05-29 10:00:38,397 - DEBUG - [Thread-10] UM.FileHandler.ReadFileJob.run [64]: Loading file took 0.0 seconds
    2018-05-29 10:00:38,414 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
    2018-05-29 10:00:38,418 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
    2018-05-29 10:00:38,419 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/ruben/Projects/Cura/cura/CuraApplication.py", line 887, in event
    2018-05-29 10:00:38,419 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     return super().event(event)
    2018-05-29 10:00:38,419 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/ruben/Projects/Uranium/UM/Qt/QtApplication.py", line 365, in event
    2018-05-29 10:00:38,420 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     event._function_event.call()
    2018-05-29 10:00:38,420 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/ruben/Projects/Uranium/UM/Event.py", line 189, in call
    2018-05-29 10:00:38,420 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     self._function(*self._args, **self._kwargs)
    2018-05-29 10:00:38,421 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/ruben/Projects/Uranium/UM/Signal.py", line 315, in __performEmit
    2018-05-29 10:00:38,421 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     func(dest, *args, **kwargs)
    2018-05-29 10:00:38,421 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/ruben/Projects/Cura/cura/CuraApplication.py", line 1503, in _reloadMeshFinished
    2018-05-29 10:00:38,421 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     mesh_data = job.getResult()[0].getMeshData()
    2018-05-29 10:00:38,422 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: IndexError: list index out of range

So to me it looks like it puts the temporary STL file as the model source in the scene node, rather than the SCAD file. It then tries to reload the STL file but it doesn't exist any more.

I think I'll add a check around this in the Cura source code but then the reload still doesn't work properly.

**Comment by thopiekar** [comment]
This is how it should work, except that it should replace the path to the temp file with the scad.
Since this is not working I assume the same bug across the other plugins, too. 🙁

**Comment by Ghostkeeper** [comment]
I tested this now with the Blender plug-in and yes it happens there too. Maybe I should put this in the common library?

**Comment by Ghostkeeper** [comment]
I've made a patch in Cura: https://github.com/Ultimaker/Cura/commit/77feb95191317a6e7bf077127a6a4d3293f67955

Now it doesn't crash any more but shows a proper error message when it failed to reload. Currently the error message says that it failed to load the /tmp/something.STL file, so reload doesn't crash it any more but still fails.

**Comment by thopiekar** [comment]
Sure, will add there a fix for it. Looks like I missed to move this part of a function to the common class of all plugins ( windows automation included).

**Comment by thopiekar** [comment]
Found the section and yes, I just made the post-processing of scene nodes, which hold the info of the paths only available for multi-app plugins, like the SolidWorks plugin, which can be in theory used with different versions installed. OpenSCAD, however, takes a more simplified logic and there I missed to apply it, too.

@Ghostkeeper , do you have an idea how it comes that Cura can't suggest a projects name and calls it "unknown"?
https://community.ultimaker.com/topic/19898-3ds-solidworks-plugin-055/?page=6&tab=comments#comment-215146

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper , do you have an idea how it comes that Cura can't suggest a projects name and calls it "unknown"?

Take a look at the [`setBaseName` function in PrintInformation.py](https://github.com/Ultimaker/Cura/blob/aa2cb7d415f6a014f4bc5a1e1cf92ea90f6b0e1e/cura/PrintInformation.py#L341). This gets called upon loading a file (I believe). We strip the extension from the file and use that to create the print job name. If the base name is empty, we have "Unknown" as name (or "Untitled" in the upcoming version).

If you're loading the files in an unusual way, such as by placing a scene object in the scene directly, then this won't trigger as it doesn't have the file name. You need to call `setBaseName` yourself then.

**Comment by thopiekar** [comment]
Already found the issue weeks before. Sorry for not keeping you up to date.
The reason was that the mime type was not registered in the new way. After that the name gets registered correctly.
